# Generated by Django 5.2.1 on 2025-05-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_remove_category_is_active_remove_product_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.category",
            ),
        ),
    ]
