# Generated by Django 5.2.1 on 2025-05-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_category_product_expense_product"),
        (
            "inventory",
            "0002_remove_category_is_active_remove_product_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.category"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="expenses.product"
            ),
        ),
    ]
