# Generated by Django 5.2.1 on 2025-05-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_category_alter_expense_product"),
        ("inventory", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
